FROM alpine:latest
LABEL maintainer="solyhe84"
# 设置工作目录
WORKDIR /app

# 复制 x86_64 平台专用文件
COPY chfs-linux-arm64 chfs
COPY chfs.ini .

EXPOSE 80
# 在运行阶段查看工作目录中的文件
RUN chmod +x chfs
CMD ["./chfs","-file=chfs.ini"]
