# 使用 Alpine 作为基础镜像
FROM alpine:latest as builder

# 设置工作目录
WORKDIR /app

# 复制 arm64 平台专用文件
COPY chfs-linux-arm64 chfs

# 最终阶段，定义运行时行为
FROM alpine:latest

# 设置工作目录
WORKDIR /app

# 从构建阶段复制文件
COPY --from=builder /app .

# 定义运行时行为
CMD ["./chfs"]
