name: Build Multi-Platform Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Set up Docker Buildx
      run: |
        docker build --platform=local -o . git://github.com/docker/buildx \
        && mkdir -p ~/.docker/cli-plugins \
        && mv buildx ~/.docker/cli-plugins/docker-buildx

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: solyhe84
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

        # 构建多平台镜像
        docker buildx build --platform linux/amd64,linux/arm64 -t solyhe84/chfs:latest .
        docker push solyhe84/chfs:latest
